### ISSUE TITLE
Cannot use WSS

### ISSUE THREAD

**Issue by joshua-small** [MoNouri97/vscode-websocket-client#1]
Connections to ws:// URI work fine, but connections to wss:// do not. Perhaps I am missing something.

I haven't used the Stomp features, but this WebSocket client is really handy :)

**Comment by MoNouri97** [comment]
This extension was only created to help me on a spring boot project so I havent done a lot of testing and bug fixing . as for why WSS doesn't work I am not sure, you can take a look at the code. In the case where you don't use stomp I am simply creating a websocket with the provided URL.

[here](https://github.com/MoNouri97/vscode-websocket-client/blob/d6196fca3ee1de4b596f2c7f7d34a7133d606fe7/web-views/components/Sidebar.svelte#L102)
`socket = new WebSocket(url);`

**Comment by alborrajo** [comment]
wss connections do work fine, however, if you're using a self signed certificate, you must launch VSCode with `code --ignore-certificate-errors` otherwise connections will fail silently
